In [1]:
kk 0

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^!kk0:起始>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


## N维数组对象

### 创建

* np.array()  
* ndarray.shape

In [2]:
c = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
%C c; c.shape

        c           c.shape
------------------  -------
[[ 1,  2,  3,  4],  (3, 4) 
 [ 4,  5,  6,  7],         
 [ 7,  8,  9, 10]]         


In [3]:
c.shape = 4, 3
c

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [4]:
c.shape = 2, -1
c

array([[ 1,  2,  3,  4,  4,  5],
       [ 6,  7,  7,  8,  9, 10]])

* ndarray.reshape()

In [5]:
a = np.array([1,2,3,4])
d = a.reshape(2,2)
%C a;d

     a           d    
------------  --------
[1, 2, 3, 4]  [[1, 2],
               [3, 4]]


In [6]:
d[0,0] = 100 
%C a;d

         a                 d      
--------------------  ------------
[100,   2,   3,   4]  [[100,   2],
                       [  3,   4]]


1. shape对原始数组进行操作, reshape则产生新的数组;    
1. 原始数组和结果数组的形状虽然不同, 但是共享数据存储空间;  
1. 通过reshape联系的两个变量(a,d), 本就是一个对象, 只是调用对象时把元素的排列方式变化了, 元素在内存中的排列顺序仍然未变;

### 元素类型

dtype做属性名: 描述数组中元素的类型

In [7]:
c.dtype

dtype('int32')

dtype做关键字参数: 指定数组中元素的类型

In [8]:
ai32 = np.array([1, 2, 3, 4], dtype=np.int32)
af = np.array([1, 2, 3, 4], dtype=float)
ac = np.array([1, 2, 3, 4], dtype=complex)

%C ai32.dtype; af.dtype; ac.dtype

  ai32.dtype        af.dtype            ac.dtype     
--------------  ----------------  -------------------
dtype('int32')  dtype('float64')  dtype('complex128')


type()是一个内嵌的函数, 返回对象所属的类;  
dtype是N维数组特有的一个属性(描述数据的类型);

In [9]:
%C c.dtype; type(c)

   c.dtype         type(c)   
--------------  -------------
dtype('int32')  numpy.ndarray


查看N维数组可存放的所有元素类型:

In [10]:
col 4 set(np.typeDict.values())

<class 'numpy.complex64'>  |<class 'numpy.complex128'> |<class 'numpy.timedelta64'> |<class 'numpy.int32'>   |
<class 'numpy.uint8'>      |<class 'numpy.float64'>    |<class 'numpy.void'>        |<class 'numpy.int64'>   |
<class 'numpy.uint32'>     |<class 'numpy.object_'>    |<class 'numpy.int8'>        |<class 'numpy.int32'>   |
<class 'numpy.uint64'>     |<class 'numpy.int16'>      |<class 'numpy.uint32'>      |<class 'numpy.str_'>    |
<class 'numpy.datetime64'> |<class 'numpy.float32'>    |<class 'numpy.bool_'>       |<class 'numpy.float64'> |
<class 'numpy.complex128'> |<class 'numpy.float16'>    |<class 'numpy.bytes_'>      |<class 'numpy.uint16'>  |



与np.float64相对应的所有字符串表示:

In [11]:
[key for key, value in np.typeDict.items() if value is np.float64]

['double', 'd', 12, 'float64', 'Float64', 'float_', 'float']

8位的二进制数可以表示哪些整数?    
* 无符号整数: 可以表示2**8=256个整数: 0->255;    
* 有符号整数: 正数范围1->127, 负数范围 -128 -> -1, 0; 无法表示整数128;

In [12]:
%C np.int8(127); np.int8(-128); np.int8(0); np.int8(128)#溢出

np.int8(127)  np.int8(-128)  np.int8(0)  np.int8(128)#溢出
------------  -------------  ----------  ---------------
127           -128           0           -128           


单个numpy数值对象的运算速度比Py内置对象的运算速度慢:

In [13]:
v1 = 3.14
v2 = np.float64(v1)
%timeit v1*v1
%timeit v2*v2

74.1 ns ± 2.13 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
128 ns ± 2.59 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


astype方法可以对数组的元素类型进行转换:

In [14]:
t1 = np.array([1, 2, 3, 4], dtype=np.float)
t2 = np.array([1, 2, 3, 4], dtype=np.complex)
t3 = t1.astype(np.int32)
t4 = t2.astype(np.complex64)
%C t1.dtype; t2.dtype; t3.dtype; t4.dtype

    t1.dtype            t2.dtype          t3.dtype          t4.dtype     
----------------  -------------------  --------------  ------------------
dtype('float64')  dtype('complex128')  dtype('int32')  dtype('complex64')


### 自动生成数组

* np.arrange(): 通过初终步长创建等差数列;

In [15]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

* np.linespace: 通过初终总长创建等差数列;
* **默认步长(包含终点)=长度/(个数-1)**;

In [16]:
np.linspace(0, 1, 10) 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.linspace(0, 1, 10, endpoint=False) # 步长为1/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

logspace根据linspace创建的等差数列创建等比数列:

In [18]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
np.logspace(0, 2, 5) # 上例的每个元素做10的幂次

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [20]:
np.logspace(0, 2, 5,base=2) # 上上例的每个元素做2的幂次

array([1.        , 1.41421356, 2.        , 2.82842712, 4.        ])

创建指定形状的特殊数组:    
* ones(): 创建全1数组;     
* zeros(): 创建全0数组;    
* empty(): 创建空数组;

In [21]:
np.zeros(4, np.complex64)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j], dtype=complex64)

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.empty((2,3), np.int)

array([[         0, 1072693248,          0],
       [1073741824,          0, 1074266112]])

* full(): 将数组初始化为指定的值;

In [24]:
np.full((3,3), np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

按参数数组的形状创建特殊数组:    
* zeros_like(), ones_like(), empty_like(), full_like();

In [25]:
c = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
np.zeros_like(c)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

从字节序列(`b'xx'`)或者文件创建数组:    
* frombuffer(), fromfile();

In [26]:
s = b'ab'  #一个字母占八位二进制数, 可以表示一个int8, 两个字母可以表示一个int16
%C np.frombuffer(s, dtype=np.int8); np.frombuffer(s, dtype=np.int16)

np.frombuffer(s, dtype=np.int8)  np.frombuffer(s, dtype=np.int16)
-------------------------------  --------------------------------
[97, 98]                         [25185]                         


In [27]:
box('ab')

  二进制    八进制    十进制    十六进制    Unicode
--------  --------  --------  ----------  ---------
 1100001       141        97        0x61          a
 1100010       142        98        0x62          b


In [28]:
bin(25185)

'0b110001001100001'

* fromfunction(func,size): 通过下标函数创建数组;

In [29]:
def func(i,j):
    return i*j
np.fromfunction(func,(3,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

自己创建特殊数组: 给定一个序列, 创建与范德蒙行列式相对应的矩阵

In [30]:
def fdm(line2=range(5)):
    """根据范德蒙行列式的第二行得与范德蒙行列式相对应的矩阵"""
    length = len(line2)
    lines = []
    for i in range(length):
        line = []
        for j in range(length):
            line.append(line2[j]**i)
        lines.append(line)
    fdm = np.array(lines, dtype=np.int32)
    return fdm

scipy库中也有创建特殊数组的函数

In [31]:
sp.linalg.hilbert(3)

array([[1.        , 0.5       , 0.33333333],
       [0.5       , 0.33333333, 0.25      ],
       [0.33333333, 0.25      , 0.2       ]])

### 存取元素

In [32]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

整数下标:

In [33]:
%C a[0]; a[9]; a[-1]

a[0]  a[9]  a[-1]
----  ----  -----
0     9     9    


In [34]:
try:
    a[10]
except Exception as e:
    print(e)

index 10 is out of bounds for axis 0 with size 10


切片下标: 切片中的 ':' 表示分隔符, 分割初,终,步长;

In [35]:
# 不能取出切片末尾元素 
%C a[:3]; a[8:9]; a[8:-1]; a[:]

  a[:3]    a[8:9]  a[8:-1]               a[:]             
---------  ------  -------  ------------------------------
[0, 1, 2]  [8]     [8]      [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [36]:
# 如果步长为负, 开始下标必须大于结束下标
%C a[1:-1:2]; a[5:1:-2]; a[::-1]

 a[1:-1:2]    a[5:1:-2]             a[::-1]            
------------  ---------  ------------------------------
[1, 3, 5, 7]  [5, 3]     [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


用下标可以用来修改元素的值:

In [37]:
a[2:4] = 20, 30
a

array([ 0,  1, 20, 30,  4,  5,  6,  7,  8,  9])

通过**切片下标**产生的新数组与原始数组**共享数据存储空间**:

In [38]:
b = a[:3]
b[0] = -100 # 将b的第1个元素修改为-100,a的第一个元素也变为-100
%C b; a[:3]

        b                 a[:3]       
------------------  ------------------
[-100,    1,   20]  [-100,    1,   20]


通过**整数序列**下标产生的新数组与原始数组**不共享存储空间**;  

In [39]:
x = np.arange(0,10)
a = x[[0,1,2,3]]
%C x; a

              x                      a      
------------------------------  ------------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  [0, 1, 2, 3]


In [40]:
a[1]=-1
%C x; a

              x                        a        
------------------------------  ----------------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  [ 0, -1,  2,  3]


整数数组作为下标, 结果数组的形状要与下标数组的形状相同;  
**不管是什么东西做下标, 新数组的形状都要与下标数组的形状相同?**: 不是

In [41]:
x[[3,3,1,8,3,3,-3,8]] # 下标数组是一维数组

array([3, 3, 1, 8, 3, 3, 7, 8])

In [42]:
x[np.array([[3,3,1,8],[3,3,-3,8]])] # 下标数组是二维数组

array([[3, 3, 1, 8],
       [3, 3, 7, 8]])

布尔数组做下标(`是否选取对应位置的值`), 首先将布尔数组转化为整数数组**nonzero()**(`要选取的位置`);

In [43]:
b  = np.arange(0,5)
ba = np.array([True, False, True, False, False],dtype=np.bool)

In [44]:
%C b; ba; ba.nonzero(); b[ba]

       b                             ba                               ba.nonzero()          b[ba] 
---------------  ------------------------------------------  -----------------------------  ------
[0, 1, 2, 3, 4]  array([ True, False,  True, False, False])  (array([0, 2], dtype=int64),)  [0, 2]


布尔列表等视为布尔数组, 但是01列表不可等视为布尔数组:

In [45]:
%C b[np.array([True, False, True, False, False])]; b[[True, False, True, False, False]]
%C b[[1, 0, 1, 0, 0]];                              b[[True, False, True, False, 0]]

b[np.array([True, False, True, False, False])]  b[[True, False, True, False, False]]
----------------------------------------------  ------------------------------------
[0, 2]                                          [0, 2]                              
b[[1, 0, 1, 0, 0]]  b[[True, False, True, False, 0]]
------------------  --------------------------------
[1, 0, 1, 0, 0]     [1, 0, 1, 0, 0]                 


布尔数组下标可以用来修改元素值:

In [46]:
b[[True, False, True, True,False]] = -1, -2, -3 
b

array([-1,  1, -2, -3,  4])

**布尔数组下标**通常情况下是由ufunc函数产生的:

In [47]:
np.random.seed(0)
x = np.random.randint(0, 10, (2,3))
%C x; x>5; x[x>5];; np.nonzero(x>5)

     x                    x>5                x[x>5]
-----------  ------------------------------  ------
[[5, 0, 3],  array([[False, False, False],   [7, 9]
 [3, 7, 9]]         [False,  True,  True]])        

                    np.nonzero(x>5)                     
--------------------------------------------------------
(array([1, 1], dtype=int64), array([1, 2], dtype=int64))


### 多维数组的索引

In [48]:
a = np.arange(0, 60, 10).reshape(-1, 1) #使用reshape将一维数组变为二维数组
b = np.arange(0, 6)
c = a + b #广播运算
%C a; b; c

  a             b                       c             
------  ------------------  --------------------------
[[ 0],  [0, 1, 2, 3, 4, 5]  [[ 0,  1,  2,  3,  4,  5],
 [10],                       [10, 11, 12, 13, 14, 15],
 [20],                       [20, 21, 22, 23, 24, 25],
 [30],                       [30, 31, 32, 33, 34, 35],
 [40],                       [40, 41, 42, 43, 44, 45],
 [50]]                       [50, 51, 52, 53, 54, 55]]


#### 一维数组或者切片做多维数组的下标元组

**下标元组的长度必须等于多维数组的维数**:   
* 缘由: 几维数组就应该有几个索引;
* 如果c是一个二维数组, c的下标必须是一个长度为2的元组;  
* 即使是`扩维运算`, 下标元组的长度也必须等于多维数组的维数;

In [49]:
%C c[0, 3:5]; c[4:, 4:]; c[:, 2]; c[2::2, ::2]

c[0, 3:5]  c[4:, 4:]           c[:, 2]            c[2::2, ::2] 
---------  ----------  ------------------------  --------------
[3, 4]     [[44, 45],  [ 2, 12, 22, 32, 42, 52]  [[20, 22, 24],
            [54, 55]]                             [40, 42, 44]]


通过切片联系的两个数组共享内存结构:

In [50]:
d = c[0,:]
%C c[0,:];d

      c[0,:]                d         
------------------  ------------------
[0, 1, 2, 3, 4, 5]  [0, 1, 2, 3, 4, 5]


In [51]:
d[1]=100
%C c[0,:];d

            c[0,:]                            d               
------------------------------  ------------------------------
[  0, 100,   2,   3,   4,   5]  [  0, 100,   2,   3,   4,   5]


In [52]:
c[0,1] = 1
%C c[0,:];d

      c[0,:]                d         
------------------  ------------------
[0, 1, 2, 3, 4, 5]  [0, 1, 2, 3, 4, 5]


创建切片对象:  
* slice(None,None,2): 创建切片对象的函数;
* np.s_: 可以创建切片对象的类;    

In [53]:
idx=np.s_[::2,2:]
idx_slice = slice(None, None, 2), slice(2,None)
%C idx; idx_slice

                    idx                                        idx_slice                  
--------------------------------------------  --------------------------------------------
(slice(None, None, 2), slice(2, None, None))  (slice(None, None, 2), slice(2, None, None))


元组或列表做多维数组的下标, 其长度必须相同:

In [54]:
%C c[(0,1,2,3),(1,2,3,4)]; c[[0,1,2,3],[1,2,3,4]]

c[(0,1,2,3),(1,2,3,4)]  c[[0,1,2,3],[1,2,3,4]]
----------------------  ----------------------
[ 1, 12, 23, 34]        [ 1, 12, 23, 34]      


切片和整数序列同时做下标元素长度可以不同:

In [55]:
c[2:, [0,2,5]]

array([[20, 22, 25],
       [30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

True, False序列可以当布尔数组, 但是0,1序列不可以当布尔数组;

In [56]:
# [True,False,True,False,False,True]
mask = np.array([1,0,1,0,0,1], dtype=np.bool) 
tup = np.array( [1,0,1,0,0,1] )
%C 5 c[mask,2]; c[tup,2]

 c[mask,2]               c[tup,2]        
------------     ------------------------
[ 2, 22, 52]     [12,  2, 12,  2,  2, 12]


元组长度不足数组维数时, 剩余的维数用`:`补足:

In [57]:
%C c[[1,2]]; c[[1,2],:]

         c[[1,2]]                   c[[1,2],:]        
--------------------------  --------------------------
[[10, 11, 12, 13, 14, 15],  [[10, 11, 12, 13, 14, 15],
 [20, 21, 22, 23, 24, 25]]   [20, 21, 22, 23, 24, 25]]


#### 二维数组或切片做多维数组的下标元组

下标元组中每个数组元素的形状都相同时: 两个数组中的元素对应起来选取一个点;

In [58]:
x = np.array([[0,1],[2,3]])
y = np.array([[-1,-2],[-3,-4]])
%C x; y; c[x,y]

   x          y         c[x,y]  
--------  ----------  ----------
[[0, 1],  [[-1, -2],  [[ 5, 14],
 [2, 3]]   [-3, -4]]   [23, 32]]


下标元素中二维数组和切片共存时要进行扩维运算:  
1. 下标元组的长度必须等于数组的维数, 不足的长度由`:`代替;  
2. 计算结果数组的形状:
    1. 不含切片时: 将所有的数组元素进行广播处理, 广播数组的形状就是结果数组的形状;
    1. 包含切片时: `数组的形状+切片形状`为结果数组的形状;

In [59]:
# x与y[0]需要进行广播 #x形状和切片形状进行组合
%C 5 x; y[0]; c[x,y[0]]; c[x]; c[x].shape

   x           y[0]       c[x,y[0]]                  c[x]                 c[x].shape
--------     --------     ----------     ----------------------------     ----------
[[0, 1],     [-1, -2]     [[ 5, 14],     [[[ 0,  1,  2,  3,  4,  5],      (2, 2, 6) 
 [2, 3]]                   [25, 34]]       [10, 11, 12, 13, 14, 15]],               
                                                                                    
                                          [[20, 21, 22, 23, 24, 25],                
                                           [30, 31, 32, 33, 34, 35]]]               


>分析:
* 该例中, 下标元组只有一个整数数组元素, 需要添加一个切片元素`:`, 整数数组x的形状为(2,2), 切片的形状(6,), 结果数组的形状应该为(2,2,6);  
* (2,2)表示行选取方式有4种, (6,)表示列选取方式有6种, 总共选取c的24个元素, 然后将其排列成(2,2,6)的形状, (2,2,6)表示一个三维数组, 含有两个二维数组, 每个二维数组的形状都是2x6;  
* 相当于将整数数组x的每个元素换成原数组c的对应行;

a,b都是二维数组, 对于切片在前的二维扩维索引**a[:,b]**:  
* 观察`a[:,b]`结果中的二维数组, 从下开始, 依次往上重叠, 最终重叠后的数组的形状便是b的形状;   
观察第一个重叠点, 从内向外依次是a第一列上的所有点;  
* 将该过程倒过来, 便可以得到结果数组的索引过程: 用后面的二维数组替换前面的切片;  
    * 根据索引的长度, 构建一个一维的空框数组;    
    * 令x=0, 将其位置替换为一个与b一起决定的的二维数组;  
    * 令x=1, 行索引为1, 列索引为b的二维数组; 
    * x = len(:)-1

In [60]:
a = np.arange(0,15).reshape(5,-1)
b = np.array([[ 0, 2, 1 ],           
              [ 2, 1, 0 ]])

In [61]:
%C 5 a; b; a[:,b]; a[:2,b]#部分行元素

      a                 b               a[:,b]          a[:2,b]#部分行元素
--------------     -----------     ----------------     -------------
[[ 0,  1,  2],     [[0, 2, 1],     [[[ 0,  2,  1],      [[[0, 2, 1], 
 [ 3,  4,  5],      [2, 1, 0]]       [ 2,  1,  0]],       [2, 1, 0]],
 [ 6,  7,  8],                                                       
 [ 9, 10, 11],                      [[ 3,  5,  4],       [[3, 5, 4], 
 [12, 13, 14]]                       [ 5,  4,  3]],       [5, 4, 3]]]
                                                                     
                                    [[ 6,  8,  7],                   
                                     [ 8,  7,  6]],                  
                                                                     
                                    [[ 9, 11, 10],                   
                                     [11, 10,  9]],                  
                                                                     
                    

2. 切片在后:
    * a[b,:], 将b中的每个元素换成a中的一行元素;  
    * a[b,i;j]: 将b中的每个元素换成a中的部分行元素;

In [62]:
palette = np.array( [[0,0,0],                
                     [255,0,0],              
                     [0,255,0],              
                     [0,0,255],              
                     [255,255,255]] )       
image = np.array( [[ 0, 1, 2, 0 ],           
                   [ 0, 3, 4, 0 ]] )
%C 5 palette; image; palette[image];palette[image,::2]#部分行元素

     palette              image             palette[image]       palette[image,::2]#部分行元素
-----------------     --------------     -------------------     ------------------------
[[  0,   0,   0],     [[0, 1, 2, 0],     [[[  0,   0,   0],      [[[  0,   0],           
 [255,   0,   0],      [0, 3, 4, 0]]       [255,   0,   0],        [255,   0],           
 [  0, 255,   0],                          [  0, 255,   0],        [  0,   0],           
 [  0,   0, 255],                          [  0,   0,   0]],       [  0,   0]],          
 [255, 255, 255]]                                                                        
                                          [[  0,   0,   0],       [[  0,   0],           
                                           [  0,   0, 255],        [  0, 255],           
                                           [255, 255, 255],        [255, 255],           
                                           [  0,   0,   0]]]       [  0,   0]]]          


### 结构数组

C语言的结构数组和numpy的结构数组可以互相转换:

**dtype** 既可以做**关键字参数**, 又可以做**属性名**, 还可以定义**结构数组类**(结构体类型), 结构数组类传递给 numpy 的dtype关键字参数, 从而定义结构体数组;

#### 字典式定义

dtype定义"结构数组类"第一个参数: `{C结构数组的字段(names):[字段列表], C结构数组的类型(formats): [类型列表]}`;

In [63]:
persontype = np.dtype( {'names':['name', 'age', 'weight'],
                        'formats':['S30','i', 'f']},align=True )
persontype

dtype({'names':['name','age','weight'], 'formats':['S30','<i4','<f4'], 'offsets':[0,32,36], 'itemsize':40}, align=True)

定义C语言结构数组: 元素的值看上去是元组,实际上是结构;   

In [64]:
a = np.array( [("Zhang", 32, 75.5),("Wang", 24, 65.2)],dtype=persontype )
a

array([(b'Zhang', 32, 75.5), (b'Wang', 24, 65.2)],
      dtype={'names':['name','age','weight'], 'formats':['S30','<i4','<f4'], 'offsets':[0,32,36], 'itemsize':40, 'aligned':True})

In [65]:
a[0]

(b'Zhang', 32, 75.5)

结构数组的类型与结构数组元素的类型相同;

In [66]:
print(a.dtype)
print(a[0].dtype)

{'names':['name','age','weight'], 'formats':['S30','<i4','<f4'], 'offsets':[0,32,36], 'itemsize':40, 'aligned':True}
{'names':['name','age','weight'], 'formats':['S30','<i4','<f4'], 'offsets':[0,32,36], 'itemsize':40, 'aligned':True}


#### 元组式定义

用元组(字段名,类型名)描述结构数组类:

In [67]:
np.dtype( [('name','|S30'),('age','<i4'),('weight','<f4')] )

dtype([('name', 'S30'), ('age', '<i4'), ('weight', '<f4')])

**字节顺序**: 字节在内存中的顺序;
* 一般情况(大端模式), 左边字节位高于右边字节位, 左边地址编号小于右边地址编号;
* **大端字节序**: 将高字节数据存放在内存低地址处, 低字节数据存放在高地址处;
* 小端字节序: 将低字节数据存放在内存低地址处, 高字节数据存放在内存高地址处;   

字段值的字节顺序:  
* `|`: 忽略字节顺序;  
* `<`:低位字节在前, 小端模式(little endian);  
* `>`:高位字节在前, 大端模式(big endian);

In [68]:
# 16进制数据: 0x3412 
print( "0x3412->大端模式(0x3412):", bin(0x3412) ) #按大端模式存储时在内存中显示的的二进制数
print( "0x3412->小端模式(0x2134):", bin(0x2134) ) #按小端模式存储时在内存中显示的的二进制数

0x3412->大端模式(0x3412): 0b11010000010010
0x3412->小端模式(0x2134): 0b10000100110100


#### 结构数组的存取

结构数组的存取方式和一般数组一样, 并且可以使用字段名作为索引:

In [69]:
# 查看结构数组中的行
%C a[0]; a[1]

        a[0]                  a[1]       
--------------------  -------------------
(b'Zhang', 32, 75.5)  (b'Wang', 24, 65.2)


In [70]:
# 查看结构数组中的列
%C a['name']; a['age']; a['weight']

               a['name']                  a['age']  a['weight'] 
----------------------------------------  --------  ------------
array([b'Zhang', b'Wang'], dtype='|S30')  [32, 24]  [75.5, 65.2]


字段既可以做结构元素的索引, 也可以做结构数组的索引

In [71]:
# 查看表中的一个确定元素
%C a[0]['name']; a[0]['age']; a[0]['weight'];;\
   a['name'][0]; a['age'][0]; a['weight'][0]

a[0]['name']  a[0]['age']  a[0]['weight']
------------  -----------  --------------
b'Zhang'      32           75.5          

a['name'][0]  a['age'][0]  a['weight'][0]
------------  -----------  --------------
b'Zhang'      32           75.5          


**a.tostring()**或**a.tofile()**方法可以将数组a以二进制的方式转换成字符串或写入文件, 文件名的后缀不能任意取;

In [72]:
a.tofile("data/test.bin")

可以读取test.bin文件的C语言程序

In [73]:
%%cell2file -o data/read_struct_array.c
#include <stdio.h>

struct person 
{
    char name[30];
    int age;
    float weight;
};

struct person p[3];

void main ()
{
    FILE *fp;
    int i;
    fp=fopen("test.bin","rb");
    fread(p, sizeof(struct person), 2, fp);
    fclose(fp);
    for(i=0;i<2;i++)
    {
        printf("%s %d %f\n", p[i].name, p[i].age, p[i].weight);
    }
}

已覆盖原文件!data/read_struct_array.c>


使用gcc编译器编译C语言程序并执行

In [74]:
%%disabled
!gcc read_struct_array.c -o read_struct_array.exe
!read_struct_array.exe

#### 结构体类型可以包含其他的结构体类型

In [75]:
kk 4

**********************************************!kk4:异常>**********************************************


In [76]:
np.dtype([('f1', [('f2', np.int16)])])

dtype([('f1', [('f2', '<i2')])])

当某个字段为结构数组时(将表格中的一个格子扩充成一张表), 用元组的第三个元素表示其形状;  

In [77]:
np.dtype([('f0', 'i4'), ('f1', 'f8', (2, 3))])

dtype([('f0', '<i4'), ('f1', '<f8', (2, 3))])

surname结构的字段名, 值为字段的类型描述, 类型描述的第二个值表示以字节为单位的偏移量

In [78]:
np.dtype({'surname':('S25',0),'age':(np.uint8,25)})

dtype([('surname', 'S25'), ('age', 'u1')])

### 内存结构

N维数组对象的数据结构(数组对象是如何在内存中存储的?):
1. 元素类型(dtype): 描述元素的类型, 是整数还是实数,字符串还是布尔值;  
1. 数据存储区域(data): 保存着数组中所有元素的二进制数据;
1. 维数和维度(dim-count,dimension): 维数表明数组是二维的还是三维的, 维度表明某个维数上的长度;  
    * A(2,2,6): 数组A的维数是3, 每一维数的长度分别是2,2,6;
1. 轴元素间隔(strides): 每个轴上相邻两个元素之间的地址差;

In [79]:
A = np.array(np.arange(9).reshape(3,3),dtype=np.float32)
A

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

查看数组元素所占的字节数

In [80]:
%C 5 A.dtype; A.dtype.itemsize

    A.dtype          A.dtype.itemsize
----------------     ----------------
dtype('float32')     4               


查看数组元素在数据存储区中的排列格式(Python坐标系: 0轴往下延伸, 1轴往右延伸):  
1. Fortran格式(MATLAB): 按列给元素地址编号, `列邻位元素`的地址差小于`行邻位元素`的地址差;  
1. C语言格式: 按行给元素地址编号, `行邻位元素`的地址差小于`列邻位`元素的地址差;  
1. Numpy数组可以使用不同的排列格式;

In [81]:
# 将A元素的排列方式设为C语言格式
A = np.array(A,dtype=np.float32, order="C")
A.flags.c_contiguous

True

In [82]:
%%disabled
# 将A元素的排列方式改为Fortran语言格式
A = np.array(A,dtype=np.float32, order="F")
A.flags.f_contiguous

flags描述了数据存储区域的一些属性:  
* C_CONTIGUOUS: 是否按C语言的格式排列元素;  
* OWNDATA: 该数组是否为内存对象的实际拥有者, 当一个数组是其他数组的视图时, 为不拥有;  
* ALIGNED: 内存对齐, 为了内存寻址的方便, C语言的结构类型会自动添加一些填充用的字节;  

In [83]:
%C A.flags.owndata; A.T.flags.owndata #A.T只是内存对象的一个视图

A.flags.owndata  A.T.flags.owndata #A.T只是内存对象的一个视图
---------------  ---------------------------------
True             False                            


**strides属性**保存每个轴上相邻两个元素的字节差(地址差):  
一个float32占4个字节, 0轴邻位元素实际还间隔了两个行元素;

In [84]:
A.strides #C格式, 4字节表示一个元素

(12, 4)

通过strides属性可以直接改变数组的排列方式, 不会放弃对内存的主权, 但会改变元素的排列格式

In [85]:
A.strides = 4,12
%C A; A.flags.owndata; A.flags.c_contiguous

      A         A.flags.owndata  A.flags.c_contiguous
--------------  ---------------  --------------------
[[0., 3., 6.],  True             False               
 [1., 4., 7.],                                       
 [2., 5., 8.]]                                       


In [86]:
# 将A元素的排列方式设为C语言格式
A = np.array(A,dtype=np.float32, order="C")
A.flags.c_contiguous

True

解释下标取得数据时引用和复制的问题

1. 切片做下标(单一整数): 无需改变数据元素在内存中的排列顺序, 调节数组属性即可实现新的表现形式(视图), 因此新数组只是内存对象的单纯引用;
1. 序列和数组(包括布尔数组)做下表时, 不能保证所选取的数据在内存区域中是等间隔的, 不能调节数组属性得到所需的表现形式, 因此会创建新的数组对象;

**base 属性** 可以获得视图数组的原始数组

In [87]:
A.T.base

array([[0., 3., 6.],
       [1., 4., 7.],
       [2., 5., 8.]], dtype=float32)

**view方法**使用不同的数值类型查看同一段内存中的二进制数据(类似frombuffer的功能?)

In [88]:
A = np.array([1],dtype=np.float32)
B = A.view(np.uint32)
C = A.view(np.int8)
%C 5 A; B; C

 A            B                      C            
----     ------------     ------------------------
[1.]     [1065353216]     [   0,    0, -128,   63]


@从一维数组创建重叠矩阵: **矩阵中的元素按某种规律重复出现**

In [89]:
from numpy.lib.stride_tricks import as_strided
a = np.arange(10)
A = as_strided(a, shape=(3, 4), strides=(4,8)) 
%C 5 a.flags.c_contiguous; a.dtype.itemsize;; a; A

a.flags.c_contiguous     a.dtype.itemsize
--------------------     ----------------
True                     4               

              a                          A       
------------------------------     --------------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]     [[0, 2, 4, 6],
                                    [1, 3, 5, 7],
                                    [2, 4, 6, 8]]


将a中的元素选入A:  
1. a中的第一个元素就是A的第一个元素;  
1. strides[0]=4: A0轴上元素的字节差为4, 即A的列邻元素就是a中的邻元素, 由此填充A的列;
1. strides[1]=8: A1轴上元素的字节差为8, 即A的行邻元素就是a中的隔一个元素的邻元素, 由此填充A的行;

In [90]:
kk 2

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$!kk2:终止>$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
