In [1]:
kk 0

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^!kk0:start>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


## 多维数组的下标存取

### 下标对象

#### 三维数组在Numpy是如何表示的

三维数组应该是三维空间中的一些离散点, 如果想要在二维平面上表示出来, 只能使用投影的方式;  
在Numpy中, 所有的三维数组都被投影在了x轴上(yoz面), 

下标对象是一个元组, 元组的长度等于多维数组的维数;   
从投影的角度理解**三维数组(3,4,5)**的含义:  
* Numpy中的空间坐标系: X轴垂直于纸面于O点(X轴垂直于纸面向上), 建立三维直角坐标系, 将其投影到纸面, 向下延伸的方向是Y轴, 向右延伸的方向是Z轴,  Y轴与Z轴之间的正向夹角是90度;
* 沿X轴向原点看去, 会遇到3个二维数组(在三个平面上), 每个二维数组的形状都是(4,5), 将这3个数组投影到yoz面上, 并依次向下错开, 就形成了三维数组的平面表示; 

沿x轴的方向向原点看过去, 所遇到的第一个数组位于平面表示的最下面, 最后一个数组位于平面表示的最上面;  
将第二个数组往上平移到第一个数组的位置, 重叠的数字其y和z坐标相同, 而x坐标不同; 例如0,20,40都是分别位于x轴上的三个元素, 其yz坐标相同, 而x位于不同的纸面高度; 

上面的的坐标轴只是自己的推测, 并没在官方文档中找到依据, 下面阐述下自己的推测:  

观察下面的输出中的第二个元素:  
1. 沿着axis=0求和时, 是对1与13的和, 因此0轴是垂直于平面的向上方向;  
2. 沿着axis=1求和时, 是对1,5,9的和, 因此1轴是平面内的垂直向上方向;  
3. 沿着axis=2求和时, 是对4,5,6,7的和, 因此2轴是平面内的水平向右方向;  
4. 有一点令人费解: 创建数组AX时先填充的是2轴元素(0,1,2,3), 然后填充1轴元素(4,8), 最后填充0轴元素(0,12)?

In [2]:
AX = np.arange(24).reshape(2,3,4)
%C 5 AX; AX.sum(axis=0); AX.sum(axis=1); AX.sum(axis=2)

         AX                AX.sum(axis=0)         AX.sum(axis=1)       AX.sum(axis=2)
--------------------     ------------------     ------------------     --------------
[[[ 0,  1,  2,  3],      [[12, 14, 16, 18],     [[12, 15, 18, 21],     [[ 6, 22, 38],
  [ 4,  5,  6,  7],       [20, 22, 24, 26],      [48, 51, 54, 57]]      [54, 70, 86]]
  [ 8,  9, 10, 11]],      [28, 30, 32, 34]]                                          
                                                                                     
 [[12, 13, 14, 15],                                                                  
  [16, 17, 18, 19],                                                                  
  [20, 21, 22, 23]]]                                                                 


#### 区别下标的类型和下标元组中元素的类型

1. `切片, 整数, 整数数组, 布尔数组`做下标对象, 相当于一个元组的元素, 如果元组长度不等于数组维数, 使用`:`补齐;  
1. 如果列表做下标, 会将一维列表变为一维数组, 二维列表变为元组;

In [3]:
a = np.arange(3 * 4 * 5).reshape(3, 4, 5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [4]:
a = np.arange(3 * 4 * 5).reshape(3, 4, 5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

切片和整数做下标元素

In [5]:
%C a[1:3,:,:]; a[1,:,:]; a[1,2,:]; a[1,2,3] 

       a[1:3,:,:]                a[1,:,:]               a[1,2,:]        a[1,2,3]
------------------------  ----------------------  --------------------  --------
[[[20, 21, 22, 23, 24],   [[20, 21, 22, 23, 24],  [30, 31, 32, 33, 34]  33      
  [25, 26, 27, 28, 29],    [25, 26, 27, 28, 29],                                
  [30, 31, 32, 33, 34],    [30, 31, 32, 33, 34],                                
  [35, 36, 37, 38, 39]],   [35, 36, 37, 38, 39]]                                
                                                                                
 [[40, 41, 42, 43, 44],                                                         
  [45, 46, 47, 48, 49],                                                         
  [50, 51, 52, 53, 54],                                                         
  [55, 56, 57, 58, 59]]]                                                        


整数数组做下标元素

In [6]:
idx = np.array( [1,2] )
idx2 = np.array( [[1,2],[1,2]] )
%C a[idx]; a[idx2] #扩维

         a[idx]                  a[idx2] #扩维        
------------------------  --------------------------
[[[20, 21, 22, 23, 24],   [[[[20, 21, 22, 23, 24],  
  [25, 26, 27, 28, 29],      [25, 26, 27, 28, 29],  
  [30, 31, 32, 33, 34],      [30, 31, 32, 33, 34],  
  [35, 36, 37, 38, 39]],     [35, 36, 37, 38, 39]], 
                                                    
 [[40, 41, 42, 43, 44],     [[40, 41, 42, 43, 44],  
  [45, 46, 47, 48, 49],      [45, 46, 47, 48, 49],  
  [50, 51, 52, 53, 54],      [50, 51, 52, 53, 54],  
  [55, 56, 57, 58, 59]]]     [55, 56, 57, 58, 59]]],
                                                    
                                                    
                           [[[20, 21, 22, 23, 24],  
                             [25, 26, 27, 28, 29],  
                             [30, 31, 32, 33, 34],  
                             [35, 36, 37, 38, 39]], 
                                                    
                            [[40, 41, 42, 43, 

列表既可以做下标也可以做下标元素:  
1. 一维列表做下标或者下标元素: 都要将其变为整数数组;   
2.   * 二维列表做下标元素, 直接将其转化为整数数组;  
    * 二维列表做下标要首先将其转化为元组, 再转化为整数数组;

In [7]:
 #一维列表或元组做下标元素, 相当于一个一维数组 
%C a[[1,2]]; a[(1,2),]; a[np.array([1,2])]; a[(1,2)] #整数元素

        a[[1,2]]                 a[(1,2),]             a[np.array([1,2])]        a[(1,2)] #整数元素   
------------------------  ------------------------  ------------------------  --------------------
[[[20, 21, 22, 23, 24],   [[[20, 21, 22, 23, 24],   [[[20, 21, 22, 23, 24],   [30, 31, 32, 33, 34]
  [25, 26, 27, 28, 29],     [25, 26, 27, 28, 29],     [25, 26, 27, 28, 29],                       
  [30, 31, 32, 33, 34],     [30, 31, 32, 33, 34],     [30, 31, 32, 33, 34],                       
  [35, 36, 37, 38, 39]],    [35, 36, 37, 38, 39]],    [35, 36, 37, 38, 39]],                      
                                                                                                  
 [[40, 41, 42, 43, 44],    [[40, 41, 42, 43, 44],    [[40, 41, 42, 43, 44],                       
  [45, 46, 47, 48, 49],     [45, 46, 47, 48, 49],     [45, 46, 47, 48, 49],                       
  [50, 51, 52, 53, 54],     [50, 51, 52, 53, 54],     [50, 51, 52, 53, 54],                       
  [55, 56,

In [8]:
# 二维列表分别做下标和下标元素
lst = [[0],[1]]
ary = np.array(lst)
%C a[lst]; a[lst,]; a[ary]

      a[lst]                a[lst,]                      a[ary]          
-----------------  --------------------------  --------------------------
[[5, 6, 7, 8, 9]]  [[[[ 0,  1,  2,  3,  4],    [[[[ 0,  1,  2,  3,  4],  
                      [ 5,  6,  7,  8,  9],       [ 5,  6,  7,  8,  9],  
                      [10, 11, 12, 13, 14],       [10, 11, 12, 13, 14],  
                      [15, 16, 17, 18, 19]]],     [15, 16, 17, 18, 19]]],
                                                                         
                                                                         
                    [[[20, 21, 22, 23, 24],     [[[20, 21, 22, 23, 24],  
                      [25, 26, 27, 28, 29],       [25, 26, 27, 28, 29],  
                      [30, 31, 32, 33, 34],       [30, 31, 32, 33, 34],  
                      [35, 36, 37, 38, 39]]]]     [35, 36, 37, 38, 39]]]]


### 整数数组作为下标

np.take(): 沿着指定轴获取元素

In [9]:
ax0 = np.take(a, indices=[0,1], axis=0)
ax1 = np.take(a, indices=[0,1], axis=1)
ax2 = np.take(a, indices=[0,1], axis=2)
%C a; ax0; ax1; ax2

           a                        ax0                       ax1                 ax2     
------------------------  ------------------------  ------------------------  ------------
[[[ 0,  1,  2,  3,  4],   [[[ 0,  1,  2,  3,  4],   [[[ 0,  1,  2,  3,  4],   [[[ 0,  1], 
  [ 5,  6,  7,  8,  9],     [ 5,  6,  7,  8,  9],     [ 5,  6,  7,  8,  9]],    [ 5,  6], 
  [10, 11, 12, 13, 14],     [10, 11, 12, 13, 14],                               [10, 11], 
  [15, 16, 17, 18, 19]],    [15, 16, 17, 18, 19]],   [[20, 21, 22, 23, 24],     [15, 16]],
                                                      [25, 26, 27, 28, 29]],              
 [[20, 21, 22, 23, 24],    [[20, 21, 22, 23, 24],                              [[20, 21], 
  [25, 26, 27, 28, 29],     [25, 26, 27, 28, 29],    [[40, 41, 42, 43, 44],     [25, 26], 
  [30, 31, 32, 33, 34],     [30, 31, 32, 33, 34],     [45, 46, 47, 48, 49]]]    [30, 31], 
  [35, 36, 37, 38, 39]],    [35, 36, 37, 38, 39]]]                              [35, 36]],

#### 下标元组中只有整数数组

In [10]:
i0 = np.array([[1, 2, 1], [0, 1, 0]])
i1 = np.array([[[0]], [[1]]])
i2 = np.array([[[2, 3, 2]]])
b = a[i0, i1, i2]
%C 5 a.shape; i0.shape; i1.shape; i2.shape; b.shape

 a.shape      i0.shape      i1.shape      i2.shape      b.shape 
---------     --------     ---------     ---------     ---------
(3, 4, 5)     (2, 3)       (2, 1, 1)     (1, 1, 3)     (2, 2, 3)


shape属性不足的部分在前面加1补齐

In [11]:
for ary in [i0,i1,i2]:
    if ary.ndim != a.ndim:
        ary.shape = (1,)*(a.ndim-ary.ndim)+ary.shape
    print(ary.shape)

(1, 2, 3)
(2, 1, 1)
(1, 1, 3)


**数组能够广播的条件**: 上面的每一列元素挖去1之外, 所有的元素都必须相同, 如果不同则不能广播;  
经过广播之后, 3个数组的形状相同, 并且这3个数组相同位置处的元素, 共同决定了该处结果数组的元素;

In [12]:
ind0, ind1, ind2 = np.broadcast_arrays(i0, i1, i2)
%C 5 ind0; ind1; ind2; b #22是a中第一个数组的0行2列

     ind0              ind1              ind2         b #22是a中第一个数组的0行2列
-------------     -------------     -------------     ------------------
[[[1, 2, 1],      [[[0, 0, 0],      [[[2, 3, 2],      [[[22, 43, 22],   
  [0, 1, 0]],       [0, 0, 0]],       [2, 3, 2]],       [ 2, 23,  2]],  
                                                                        
 [[1, 2, 1],       [[1, 1, 1],       [[2, 3, 2],       [[27, 48, 27],   
  [0, 1, 0]]]       [1, 1, 1]]]       [2, 3, 2]]]       [ 7, 28,  7]]]  


#### 下标元组中既有整数数组又有切片

下标含有切片时, 应遵循一般的索引规则: 索引在前和索引在后的形式(**后面数组替换前面数组的空框形式**);  
1. 切片在后:  
    * 将整数数组进行广播, 写出广播数组的结构表示为`空框形式`;  
    * 将每个空框换成切片代表的一维数组;
1. 切片在前:  
    * 将切片表示为`空框形式`; 
    * 令x分别为切片的每个索引, 配合其余数组得到的部分结果数组;  
    * 将部分结果数组放入切片的空框形式;

切片位于整数数组们的两侧: 原位组合切片的形状和广播数组的形状, 得结果数组的形状

In [13]:
c = a[:, i0, i1]
ind0,ind2 = np.broadcast_arrays(i0, i1)  #数组a的第一个轴的长度是3, 切片的长度是3
%C 5 ind0.shape; ind2.shape; c.shape; c.shape == (3,)+ind0.shape

ind0.shape     ind2.shape       c.shape        c.shape == (3,)+ind0.shape
----------     ----------     ------------     --------------------------
(2, 2, 3)      (2, 2, 3)      (3, 2, 2, 3)     True                      


In [14]:
%C 5 ind0; ind1; a; c

     ind0              ind1                    a                         c         
-------------     -------------     ------------------------     ------------------
[[[1, 2, 1],      [[[0, 0, 0],      [[[ 0,  1,  2,  3,  4],      [[[[ 5, 10,  5],  
  [0, 1, 0]],       [0, 0, 0]],       [ 5,  6,  7,  8,  9],         [ 0,  5,  0]], 
                                      [10, 11, 12, 13, 14],                        
 [[1, 2, 1],       [[1, 1, 1],        [15, 16, 17, 18, 19]],       [[ 6, 11,  6],  
  [0, 1, 0]]]       [1, 1, 1]]]                                     [ 1,  6,  1]]],
                                     [[20, 21, 22, 23, 24],                        
                                      [25, 26, 27, 28, 29],                        
                                      [30, 31, 32, 33, 34],       [[[25, 30, 25],  
                                      [35, 36, 37, 38, 39]],        [20, 25, 20]], 
                                                                            

整数数组不连续, 切片在中间时结果数组的形状: 将切片的形状放在其他数组广播之后的形状的后面;

In [15]:
d = a[i0, :, i1] #数组a第二个轴的长度是4, 切片的长度也是4
%C ind0.shape; d.shape

ind0.shape    d.shape   
----------  ------------
(2, 2, 3)   (2, 2, 3, 4)


In [16]:
%C ind0; ind1; a; d

     ind0           ind1                 a                        d           
-------------  -------------  ------------------------  ----------------------
[[[1, 2, 1],   [[[0, 0, 0],   [[[ 0,  1,  2,  3,  4],   [[[[20, 25, 30, 35],  
  [0, 1, 0]],    [0, 0, 0]],    [ 5,  6,  7,  8,  9],      [40, 45, 50, 55],  
                                [10, 11, 12, 13, 14],      [20, 25, 30, 35]], 
 [[1, 2, 1],    [[1, 1, 1],     [15, 16, 17, 18, 19]],                        
  [0, 1, 0]]]    [1, 1, 1]]]                              [[ 0,  5, 10, 15],  
                               [[20, 21, 22, 23, 24],      [20, 25, 30, 35],  
                                [25, 26, 27, 28, 29],      [ 0,  5, 10, 15]]],
                                [30, 31, 32, 33, 34],                         
                                [35, 36, 37, 38, 39]],                        
                                                         [[[21, 26, 31, 36],  
                               [[40, 41, 42, 43, 44]

> 往ind0, ind1的空框形式, 填充元素;  
左上角的第一个元素: 0(x)轴索引1, 2(z)轴索引0, 1(y)轴索引全要 => [20,25,30,35]

In [17]:
d = a[i0,i1,:] #数组a第3个轴的长度是5, 切片的长度也是5
%C ind0; ind1; a; d

     ind0           ind1                 a                          d             
-------------  -------------  ------------------------  --------------------------
[[[1, 2, 1],   [[[0, 0, 0],   [[[ 0,  1,  2,  3,  4],   [[[[20, 21, 22, 23, 24],  
  [0, 1, 0]],    [0, 0, 0]],    [ 5,  6,  7,  8,  9],      [40, 41, 42, 43, 44],  
                                [10, 11, 12, 13, 14],      [20, 21, 22, 23, 24]], 
 [[1, 2, 1],    [[1, 1, 1],     [15, 16, 17, 18, 19]],                            
  [0, 1, 0]]]    [1, 1, 1]]]                              [[ 0,  1,  2,  3,  4],  
                               [[20, 21, 22, 23, 24],      [20, 21, 22, 23, 24],  
                                [25, 26, 27, 28, 29],      [ 0,  1,  2,  3,  4]]],
                                [30, 31, 32, 33, 34],                             
                                [35, 36, 37, 38, 39]],                            
                                                         [[[25, 26, 27, 28, 29],  
    

> 往ind0, ind1的空框形式, 填充元素;  
左上角的第一个元素: 0(x)轴索引1, 1(y)轴索引0, 2(y)轴索引全要 => [20,21,22,23,24]

In [18]:
kk 4

*********************************************!kk4:pass>*********************************************


### 一个复杂的例子

已知整数`L`, 数组`v`及其形状: 
* `v.shape = I,J,K`  
* `idx.shape = I,J`, idx的每个值都是`0到K-L`之间的整数  

求满足`r[i,j,:] = v[i,j,idx[i,j]:idx[i,j]+L]`的数组`r`

In [19]:
I, J, K, L = 3, 4, 5, 3

# 数组v: 在z轴上, 每层的值都是该层的高度
_, _, v = np.mgrid[:I, :J, :K]

# 随机产生数组idx, 它的每个元素都在0到K-L之间
idx = np.random.randint(0, K - L, size=(I, J))

# 创建第0轴和第1轴的下标数组
idx_i, idx_j, _ = np.ogrid[:I, :J, :K]

# 创建第2轴的下标数组
idx_k = idx[:, :, None] + np.arange(L)

r = v[idx_i, idx_j, idx_k]    

%C 3 v; idx; idx_i; idx_j; idx_k; r ;;\
                                    v.shape; idx.shape; idx_i.shape; idx_j.shape; idx_k.shape; r.shape

         v                 idx          idx_i     idx_j        idx_k             r      
-------------------   --------------   -------   -------   -------------   -------------
[[[0, 1, 2, 3, 4],    [[0, 0, 1, 1],   [[[0]],   [[[0],    [[[0, 1, 2],    [[[0, 1, 2], 
  [0, 1, 2, 3, 4],     [0, 1, 0, 1],               [1],      [0, 1, 2],      [0, 1, 2], 
  [0, 1, 2, 3, 4],     [1, 1, 0, 0]]    [[1]],     [2],      [1, 2, 3],      [1, 2, 3], 
  [0, 1, 2, 3, 4]],                                [3]]]     [1, 2, 3]],     [1, 2, 3]],
                                        [[2]]]                                          
 [[0, 1, 2, 3, 4],                                          [[0, 1, 2],     [[0, 1, 2], 
  [0, 1, 2, 3, 4],                                           [1, 2, 3],      [1, 2, 3], 
  [0, 1, 2, 3, 4],                                           [0, 1, 2],      [0, 1, 2], 
  [0, 1, 2, 3, 4]],                                          [1, 2, 3]],     [1, 2, 3]],
                     

### 布尔数组作下标

若只需要沿着指定轴通过布尔数组获取元素, 可以使用`np.compress()`函数

In [20]:
ax0 = np.compress([True, True, False], a, axis=0)
ax1 = np.compress([True, True, False], a, axis=1)
ax2 = np.compress([True, True, False], a, axis=2)
%C a; ax0; ax1; ax2

           a                        ax0                       ax1                 ax2     
------------------------  ------------------------  ------------------------  ------------
[[[ 0,  1,  2,  3,  4],   [[[ 0,  1,  2,  3,  4],   [[[ 0,  1,  2,  3,  4],   [[[ 0,  1], 
  [ 5,  6,  7,  8,  9],     [ 5,  6,  7,  8,  9],     [ 5,  6,  7,  8,  9]],    [ 5,  6], 
  [10, 11, 12, 13, 14],     [10, 11, 12, 13, 14],                               [10, 11], 
  [15, 16, 17, 18, 19]],    [15, 16, 17, 18, 19]],   [[20, 21, 22, 23, 24],     [15, 16]],
                                                      [25, 26, 27, 28, 29]],              
 [[20, 21, 22, 23, 24],    [[20, 21, 22, 23, 24],                              [[20, 21], 
  [25, 26, 27, 28, 29],     [25, 26, 27, 28, 29],    [[40, 41, 42, 43, 44],     [25, 26], 
  [30, 31, 32, 33, 34],     [30, 31, 32, 33, 34],     [45, 46, 47, 48, 49]]]    [30, 31], 
  [35, 36, 37, 38, 39]],    [35, 36, 37, 38, 39]]]                              [35, 36]],

#### 布尔数组转化为一组整数数组

**nonezero():**  
1. 如果布尔数组的维数是1, 直接返回布尔数组中的`True`元素所在的下标;

In [21]:
b = np.array([True, False, True, False])
b.nonzero()

(array([0, 2], dtype=int64),)

2. 如果数组的维数大于1, 返回True元素所在下标之后, 将每个轴上的元素提取出来保存在对应的轴列表中;

In [22]:
b2 = np.array([[True, False, True], 
              [True, False, False]])
b2.nonzero()

(array([0, 0, 1], dtype=int64), array([0, 2, 0], dtype=int64))

In [23]:
# %%disabled np.nonzero的过程
id_true = [(0,0), 
           (0,2), 
           (1,0)]  # True元素所在的下标
id0, id1 = [], []  # 将每个轴的坐标保存在对应的轴列表中
for i in id_true:
    id0.append(i[0])
    id1.append(i[1])
%C id0; id1

   id0        id1   
---------  ---------
[0, 0, 1]  [0, 2, 0]


3. np.nonzero()对三维数组的处理

In [24]:
np.random.seed(42)
b3=np.random.randint(0,2,(1,2,3), dtype=np.bool)
%C b3; b3.nonzero()

            b3                       b3.nonzero()         
-------------------------  -------------------------------
[[[False,  True,  True],   (array([0, 0, 0], dtype=int64),
  [False, False,  True]]]   array([0, 0, 1], dtype=int64),
                            array([1, 2, 2], dtype=int64))


#### 布尔数组如何做下标

布尔数组也称为遮罩数组: 将布尔数组覆盖在原数组之上, 被True元素压住的元素将被取出

In [25]:
a3 = np.arange(1 * 2 * 3).reshape(1, 2, 3)
%C a3; a3[b3]; a3[[0,0,0], [0,0,1], [1,2,2]] #b3对应的整数数组

      a3         a3[b3]   a3[[0,0,0], [0,0,1], [1,2,2]] #b3对应的整数数组
-------------  ---------  ----------------------------------------
[[[0, 1, 2],   [1, 2, 5]  [1, 2, 5]                               
  [3, 4, 5]]]                                                     


下标元组既有切片又有布尔数组(布尔数组做下标元素):

In [26]:
A = np.arange(60).reshape(3,4,5)
A

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [27]:
a2 = np.arange(3*2*3).reshape(3,2,3)
%C a2; b2; b2.nonzero()

       a2                    b2                                     b2.nonzero()                         
----------------  -----------------------  --------------------------------------------------------------
[[[ 0,  1,  2],   [[ True, False,  True],  (array([0, 0, 1], dtype=int64), array([0, 2, 0], dtype=int64))
  [ 3,  4,  5]],   [ True, False, False]]                                                                
                                                                                                         
 [[ 6,  7,  8],                                                                                          
  [ 9, 10, 11]],                                                                                         
                                                                                                         
 [[12, 13, 14],                                                                                          
  [15, 16, 17]]]                              

1. 从布尔数组遮罩的角度:   
    * x=0, 三维数组的第一个二维数组;
    * 使用遮罩数组b2盖住这个二维数组, 取其中的True压元素 => [0,2,3];  
    * 依次将切片框替换为遮罩数组对应的一行元素;  
1. 从整数数组的角度:  
    * [0,0,1],[0,2,0]扩维后的框架为[X,X,X];
    * 切片的框架为[P,P,P];
    * x=0时扩维数组表示[0,2,3];
    * 使用[0,2,3]替换切片框架中的第一个P;

In [28]:
%C a2[:,b2];  a2[:,[0,0,1],[0,2,0]]

   a2[:,b2]     a2[:,[0,0,1],[0,2,0]]
--------------  ---------------------
[[ 0,  2,  3],  [[ 0,  2,  3],       
 [ 6,  8,  9],   [ 6,  8,  9],       
 [12, 14, 15]]   [12, 14, 15]]       


In [29]:
kk 2

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$!kk2:end>$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
