In [2]:
# @
import numpy as np
from brtoz import brmagic

In [173]:
%precision 3

'%.3f'

## ndarray对象

### 创建

* np.array()  
* ndarray.shape

In [136]:
c = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
%ap c; c.shape

        c           c.shape
------------------  -------
[[ 1,  2,  3,  4],  (3, 4) 
 [ 4,  5,  6,  7],         
 [ 7,  8,  9, 10]]         


In [137]:
c.shape = 4, 3
c

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [138]:
c.shape = 2, -1
c

array([[ 1,  2,  3,  4,  4,  5],
       [ 6,  7,  7,  8,  9, 10]])

* ndarray.reshape()

In [141]:
a = np.array([1,2,3,4])
d = a.reshape(2,2)
%ap a;d

     a           d    
------------  --------
[1, 2, 3, 4]  [[1, 2],
               [3, 4]]


In [144]:
d[0,0] = 100 

In [145]:
%ap a;d

         a                 d      
--------------------  ------------
[100,   2,   3,   4]  [[100,   2],
                       [  3,   4]]


> shape对原始数组进行操作, reshape则产生新的数组;    
> 虽然原始数组和结果数组形状不同, 但是共享数据存储空间;

### 元素类型

dtype做属性名:

In [146]:
c.dtype

dtype('int32')

dtype做关键字参数:

In [153]:
ai32 = np.array([1, 2, 3, 4], dtype=np.int32)
af = np.array([1, 2, 3, 4], dtype=float)
ac = np.array([1, 2, 3, 4], dtype=complex)

%ap ai32.dtype; af.dtype; ac.dtype

  ai32.dtype        af.dtype            ac.dtype     
--------------  ----------------  -------------------
dtype('int32')  dtype('float64')  dtype('complex128')


dtype属性和type属性是不同的;

In [154]:
%ap c.dtype; c.dtype.type

   c.dtype      c.dtype.type
--------------  ------------
dtype('int32')  numpy.int32 


输出numpy中所有的类型名:

In [155]:
set(np.typeDict.values())

{numpy.bool_,
 numpy.bytes_,
 numpy.complex128,
 numpy.complex128,
 numpy.complex64,
 numpy.datetime64,
 numpy.float16,
 numpy.float32,
 numpy.float64,
 numpy.float64,
 numpy.int16,
 numpy.int32,
 numpy.int32,
 numpy.int64,
 numpy.int8,
 numpy.object_,
 numpy.str_,
 numpy.timedelta64,
 numpy.uint16,
 numpy.uint32,
 numpy.uint32,
 numpy.uint64,
 numpy.uint8,
 numpy.void}

输出np.float64的所有字符串表示:

In [194]:
[key for key, value in np.typeDict.items() if value is np.float64]

['double', 'd', 12, 'float64', 'Float64', 'float_', 'float']

溢出:

In [188]:
2**16/2-1 #32767是可以表示的最大正数

32767.000

In [189]:
%ap np.int16(32768); np.int16(-32768) 

np.int16(32768)  np.int16(-32768)
---------------  ----------------
-32768           -32768          


>16位的二进制数可以表示哪些整数?    
* 无符号整数: 可以表示2**16=65536个整数: 0->65535;    
* 有符号整数: 正数范围1->32767, 负数范围 -1 -> 32768, 0;

单个numpy数值对象的运算速度比Py内置对象的运算速度慢:

In [190]:
v1 = 3.14
v2 = np.float64(v1)
%timeit v1*v1
%timeit v2*v2

71.5 ns ± 0.833 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
127 ns ± 0.415 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


astype方法可以对数组的元素类型进行转换:

In [193]:
t1 = np.array([1, 2, 3, 4], dtype=np.float)
t2 = np.array([1, 2, 3, 4], dtype=np.complex)
t3 = t1.astype(np.int32)
t4 = t2.astype(np.complex64)
%ap t1.dtype; t2.dtype; t3.dtype; t4.dtype

    t1.dtype            t2.dtype          t3.dtype          t4.dtype     
----------------  -------------------  --------------  ------------------
dtype('float64')  dtype('complex128')  dtype('int32')  dtype('complex64')


### 自动生成数组

* np.arrange(): 通过初终步长创建等差数列;

In [195]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

* np.linespace: 通过初终总长创建等差数列;
* **默认步长(包含终点)=长度/(个数-1)**;
* 不包含终点时, 步长个数就是终点值;

In [196]:
np.linspace(0, 1, 10) 

array([0.   , 0.111, 0.222, 0.333, 0.444, 0.556, 0.667, 0.778, 0.889,
       1.   ])

In [197]:
np.linspace(0, 1, 10, endpoint=False) # 步长为1/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

logspace根据linspace创建的等差数列创建等比数列:

In [198]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [200]:
np.logspace(0, 2, 5) # 上例的每个元素做10的幂次

array([  1.   ,   3.162,  10.   ,  31.623, 100.   ])

In [202]:
np.logspace(0, 2, 5,base=2) # 上上例的每个元素做2的幂次

array([1.   , 1.414, 2.   , 2.828, 4.   ])

创建指定形状特殊数组:    
* ones(): 创建全1数组;     
* zeros(): 创建全0数组;    
* empty(): 创建空数组;

In [203]:
np.zeros(4, np.complex64)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j], dtype=complex64)

In [204]:
np.ones(4)

array([1., 1., 1., 1.])

In [205]:
np.empty((2,3), np.int)

array([[         0, 1072168960,          0],
       [1072168960,          0,          0]])

* full(): 将数组初始化为指定的值;

In [206]:
np.full((3,4), np.pi)

array([[3.142, 3.142, 3.142, 3.142],
       [3.142, 3.142, 3.142, 3.142],
       [3.142, 3.142, 3.142, 3.142]])

按参数数组的形状创建特殊数组:    
* zeros_like(), ones_like(), empty_like(), full_like();

In [214]:
c = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
np.zeros_like(c)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

从字节数列或者文件创建数组:    
* frombuffer(), fromstring(), fromfile();

In [239]:
s = 'abcdefgh'
#一个字母相当于一个八位二进制数, 八个字母相当于一个float64的浮点数

In [240]:
%ap np.fromstring(s, dtype=np.float64);;np.fromstring(s, dtype=np.int8)

np.fromstring(s, dtype=np.float64)
----------------------------------
[8.541e+194]                      

    np.fromstring(s, dtype=np.int8)     
----------------------------------------
[ 97,  98,  99, 100, 101, 102, 103, 104]


C:\Users\tfliu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


* fromfunction(func,size): 通过下标函数创建数组;

In [246]:
def func(i,j):
    return (i+1)*(j+1)
np.fromfunction(func,(3,4))

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  4.,  6.,  8.],
       [ 3.,  6.,  9., 12.]])

### 存取元素

In [292]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

整数下标:

In [293]:
%ap a[0]; a[9]; a[-1]

a[0]  a[9]  a[-1]
----  ----  -----
0     9     9    


In [294]:
try:
    a[10]
except Exception as e:
    print(e)

index 10 is out of bounds for axis 0 with size 10


切片下标: 切片中的 ':' 表示分隔符, 分割初,终,步长;

In [295]:
# 不能取出切片末尾元素 
%ap a[:3]; a[8:9]; a[8:-1]; a[:]

  a[:3]    a[8:9]  a[8:-1]               a[:]             
---------  ------  -------  ------------------------------
[0, 1, 2]  [8]     [8]      [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [296]:
# 如果步长为负, 开始下标必须大于结束下标
%ap a[1:-1:2]; a[5:1:-2]; a[::-1]

 a[1:-1:2]    a[5:1:-2]             a[::-1]            
------------  ---------  ------------------------------
[1, 3, 5, 7]  [5, 3]     [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


用下标可以用来修改元素的值:

In [297]:
a[2:4] = 20, 30
a

array([ 0,  1, 20, 30,  4,  5,  6,  7,  8,  9])

通过**切片下标**产生的新数组与原始数组**共享数据存储空间**:

In [362]:
b = a[:3]
b[0] = -100 # 将b的第1个元素修改为-100,a的第一个元素也变为-100
%ap b; a[:3]

        b                 a[:3]       
------------------  ------------------
[-100,   -1,    2]  [-100,   -1,    2]


通过**整数序列**下标产生的新数组与原始数组**不共享存储空间**:

In [363]:
x = np.arange(0,10)
a = x[[0,1,2,3]]
%ap x; a

              x                      a      
------------------------------  ------------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  [0, 1, 2, 3]


In [364]:
a[1]=-1
%ap x; a

              x                        a        
------------------------------  ----------------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  [ 0, -1,  2,  3]


整数数组作为下标, 结果数组的形状要与下标数组的形状相同:

In [365]:
x[[3,3,1,8,3,3,-3,8]] # 下标数组是一维数组

array([3, 3, 1, 8, 3, 3, 7, 8])

In [366]:
x[np.array([[3,3,1,8],[3,3,-3,8]])] # 下标数组是二维数组

array([[3, 3, 1, 8],
       [3, 3, 7, 8]])

布尔数组做下标, 首先将布尔数组转化为整数数组**nonzero()**;

In [367]:
b1  = np.arange(0,5)
ba = np.array([True, False, True, False, False])
%ap b1;ba;b1[ba];; ba.nonzero();np.nonzero(ba)

       b1                         ba                  b1[ba]
---------------  -----------------------------------  ------
[0, 1, 2, 3, 4]  [ True, False,  True, False, False]  [0, 2]

         ba.nonzero()                  np.nonzero(ba)       
-----------------------------  -----------------------------
(array([0, 2], dtype=int64),)  (array([0, 2], dtype=int64),)


布尔列表等视为布尔数组:

In [368]:
%ap b1[[True, False, True, False, False]];\
                       b1[np.array([True, False, True, False, False])]

b1[[True, False, True, False, False]]  b1[np.array([True, False, True, False, False])]
-------------------------------------  -----------------------------------------------
[0, 2]                                 [0, 2]                                         


01列表不可等视为布尔数组:

In [369]:
b1[[1, 0, 1, 0, 0]] 

array([1, 0, 1, 0, 0])

布尔数组下标可以用来修改元素值:

In [370]:
b1[[True, False, True, True,False]] = -1, -2, -3 
b1

array([-1,  1, -2, -3,  4])

**布尔数组下标**通常情况下是由ufunc函数产生的:

In [377]:
np.random.seed(0)
x = np.random.randint(0, 10, (2,3))
%ap x; x>5; x[x>5];; np.nonzero(x>5)

     x                 x>5            x[x>5]
-----------  -----------------------  ------
[[5, 0, 3],  [[False, False, False],  [7, 9]
 [3, 7, 9]]   [False,  True,  True]]        

                    np.nonzero(x>5)                     
--------------------------------------------------------
(array([1, 1], dtype=int64), array([1, 2], dtype=int64))


### 多维数组

In [390]:
a = np.arange(0, 60, 10).reshape(-1, 1) 
b = np.arange(0, 6)
c = a + b
%ap a; b; c

  a             b                       c             
------  ------------------  --------------------------
[[ 0],  [0, 1, 2, 3, 4, 5]  [[ 0,  1,  2,  3,  4,  5],
 [10],                       [10, 11, 12, 13, 14, 15],
 [20],                       [20, 21, 22, 23, 24, 25],
 [30],                       [30, 31, 32, 33, 34, 35],
 [40],                       [40, 41, 42, 43, 44, 45],
 [50]]                       [50, 51, 52, 53, 54, 55]]


**下标元组的长度==多维数组的维数**:

In [391]:
%ap c[0, 3:5]; c[4:, 4:]; c[:, 2]; c[2::2, ::2]

c[0, 3:5]  c[4:, 4:]           c[:, 2]            c[2::2, ::2] 
---------  ----------  ------------------------  --------------
[3, 4]     [[44, 45],  [ 2, 12, 22, 32, 42, 52]  [[20, 22, 24],
            [54, 55]]                             [40, 42, 44]]


通过切片联系的两个数组共享内存结构:

In [ ]:
d = c[0,:]
%ap c[0,:];d

In [394]:
d[1]=100
%ap c[0,:];d

            c[0,:]                            d               
------------------------------  ------------------------------
[  0, 100,   2,   3,   4,   5]  [  0, 100,   2,   3,   4,   5]


* np.s_: 可以创建切片对象的类    
* slice(None,None,2): 创建切片对象的函数

In [399]:
idx_slice = slice(None, None, 2), slice(2,None)
%ap idx_slice; 

                 idx_slice                       c[idx_slice]   
--------------------------------------------  ------------------
(slice(None, None, 2), slice(2, None, None))  [[ 2,  3,  4,  5],
                                               [22, 23, 24, 25],
                                               [42, 43, 44, 45]]


In [401]:
idx_s=np.s_[::2,2:]
%ap idx_s; c[idx_s]

                   idx_s                           c[idx_s]     
--------------------------------------------  ------------------
(slice(None, None, 2), slice(2, None, None))  [[ 2,  3,  4,  5],
                                               [22, 23, 24, 25],
                                               [42, 43, 44, 45]]


整数元组或整数序列, 做多维数组的下标, 其长度必须相同:

In [425]:
%ap c[(0,1,2,3),(1,2,3,4)]; c[[0,1,2,3],[1,2,3,4]]

c[(0,1,2,3),(1,2,3,4)]  c[[0,1,2,3],[1,2,3,4]]
----------------------  ----------------------
[100,  12,  23,  34]    [100,  12,  23,  34]  


切片和整数序列同时做下标元素长度可以不同:

In [426]:
%ap c[2:, [0,2,5]]

c[2:, [0,2,5]]
--------------
[[20, 22, 25],
 [30, 32, 35],
 [40, 42, 45],
 [50, 52, 55]]


True, False序列可以当布尔数组, 但是0,1序列不可以当布尔数组;

In [427]:
# [True,False,True,False,False,True]
mask_b = np.array([1,0,1,0,0,1], dtype=np.bool) 
mask_l = np.array( [1,0,1,0,0,1] )
%ap c[mask_b,2]; c[mask_l,2]

c[mask_b,2]         c[mask_l,2]       
------------  ------------------------
[ 2, 22, 52]  [12,  2, 12,  2,  2, 12]


下标元组的长度必须许等于原始数组的维数 (几维数组就应该有几个索引):

In [431]:
%ap c[[1,2],:]; c[[1,2]]

        c[[1,2],:]                   c[[1,2]]         
--------------------------  --------------------------
[[10, 11, 12, 13, 14, 15],  [[10, 11, 12, 13, 14, 15],
 [20, 21, 22, 23, 24, 25]]   [20, 21, 22, 23, 24, 25]]


In [433]:
x = np.array([[0,1],[2,3]])
y = np.array([[-1,-2],[-3,-4]])
%ap x; y; c[x,y]

   x          y         c[x,y]  
--------  ----------  ----------
[[0, 1],  [[-1, -2],  [[ 5, 14],
 [2, 3]]   [-3, -4]]   [23, 32]]


>下标是一个长度为2的元组, 这个元组的每个元素都是一个二维数组, 并且这两个二维数组的形状相同;

数组的下标运算可以扩展维度:

In [443]:
%ap c; x; c[x]

               c                     x                     c[x]               
--------------------------------  --------  ----------------------------------
[[  0, 100,   2,   3,   4,   5],  [[0, 1],  [[[  0, 100,   2,   3,   4,   5], 
 [ 10,  11,  12,  13,  14,  15],   [2, 3]]    [ 10,  11,  12,  13,  14,  15]],
 [ 20,  21,  22,  23,  24,  25],                                              
 [ 30,  31,  32,  33,  34,  35],             [[ 20,  21,  22,  23,  24,  25], 
 [ 40,  41,  42,  43,  44,  45],              [ 30,  31,  32,  33,  34,  35]]]
 [ 50,  51,  52,  53,  54,  55]]                                              


>分析:
    X是二维数组, 因此需要两个索引,下标元组的长度应该是2, 不足的长度由 : 代替;
    下标元素既包含整数数组又包含切片时, 结果数组的形状为整数数组广播后的形状与切片形状的组合, 整数数组连续时, 进行原序组合, 不连续时, 将切片位放在最后;

>    `a[x] 整数数组 x 的形状 (2,2), 切片的形状 (6,), 结果数组的形状(2,2,6). (2,2) 表示 a 的行选取方式有 4 种, (6,) 表示 a 的列选取方式有 6 种, 总共选取 a 的24个元素, 然后将其排列成 (2,2,6) 的形状. 也可以认为将整数数组 x 的每个元素换成 a 的 某一行;`

对于 **a[idx]**的下标索引(a和idx都是二维数组)**, 只需将下标元组(第一个元素,二维数组)的每个元素换成原数组的一行即可;

In [448]:
palette = np.array( [[0,0,0],                
                     [255,0,0],              
                     [0,255,0],              
                     [0,0,255],              
                     [255,255,255]] )       
image = np.array( [[ 0, 1, 2, 0 ],           
                   [ 0, 3, 4, 0 ]] )
%ap palette; image; palette[image];palette[image,:]

     palette           image          palette[image]      palette[image,:] 
-----------------  --------------  -------------------  -------------------
[[  0,   0,   0],  [[0, 1, 2, 0],  [[[  0,   0,   0],   [[[  0,   0,   0], 
 [255,   0,   0],   [0, 3, 4, 0]]    [255,   0,   0],     [255,   0,   0], 
 [  0, 255,   0],                    [  0, 255,   0],     [  0, 255,   0], 
 [  0,   0, 255],                    [  0,   0,   0]],    [  0,   0,   0]],
 [255, 255, 255]]                                                          
                                    [[  0,   0,   0],    [[  0,   0,   0], 
                                     [  0,   0, 255],     [  0,   0, 255], 
                                     [255, 255, 255],     [255, 255, 255], 
                                     [  0,   0,   0]]]    [  0,   0,   0]]]


>如何加速反应下标运算的结果?

### 结构数组

C语言的结构数组和numpy的结构数组可以互相转换:

**dtype** 既可以做**关键字参数**, 又可以做**属性名**, 还可以定义**结构数组类**, 结构数组类传递给 numpy 的dtype关键字参数, 从而定义结构体数组;

dtype定义"结构数组类"时用一个字典作为第一个参数, 字典的有两个键, 分别表示字段(names)和类型(formats);

In [5]:
persontype = np.dtype( {'names':['name', 'age', 'weight'],
                        'formats':['S30','i', 'f']},align=True )
a = np.array( [("Zhang", 32, 75.5),("Wang", 24, 65.2)],dtype=persontype )
%ap a; a[0]
print('\n')
print(a.dtype)
print(a[0].dtype)

                     a                               a[0]        
-------------------------------------------  --------------------
[(b'Zhang', 32, 75.5), (b'Wang', 24, 65.2)]  (b'Zhang', 32, 75.5)


{'names':['name','age','weight'], 'formats':['S30','<i4','<f4'], 'offsets':[0,32,36], 'itemsize':40, 'aligned':True}
{'names':['name','age','weight'], 'formats':['S30','<i4','<f4'], 'offsets':[0,32,36], 'itemsize':40, 'aligned':True}


>元素的值看上去是元组,实际上是结构;    
 结构数组的类型由结构数组元素的类型决定;

还可以用元组 (字段名,类型名) 列表来描述结构数组类:

In [ ]:
np.dtype( [('name','|S30'),('age','<i4'),('weight','<f4')] )

In [16]:
# 16进制数据: 0x3412 
print( "0x3412->大端模式(0x3412):", 0x3412 )#按大端模式存储时表示的十进制数据
print( "0x3412->小端模式(0x1234):", 0x1234 ) #按小端模式存储时表示的十进制数据

0x3412->大端模式(0x3412): 13330
0x3412->小端模式(0x1234): 4660


> **字节顺序**: 字节在内存中的顺序;
* 一般情况(大端模式), 左边字节位高于右边字节位, 左边地址编号小于右边地址编号;
* **大端字节序**: 将高字节数据存放在内存低地址处, 低字节数据存放在高地址处;
* 小端字节序: 将低字节数据存放在内存低地址处, 高字节数据存放在内存高地址处;   

结构数组的存取方式和一般数组一样, 可把结构数组当成一张表, 下标相当于表的行列索引;

In [32]:
%ap 5 a;a[0];; a[0]["name"];a['name']        
print("\n[0]行索引,['name']列索引")

                     a                                  a[0]        
-------------------------------------------     --------------------
[(b'Zhang', 32, 75.5), (b'Wang', 24, 65.2)]     (b'Zhang', 32, 75.5)

a[0]["name"]          a['name']     
------------     -------------------
b'Zhang'         [b'Zhang', b'Wang']

[0]行索引,['name']列索引


> 可以用字段名获得对应的字段值, 这里的字段既可以是结构元素的字段, 也可以是结构数组的字段

a.tostring() 或 a.tofile() 方法 可以将数组 a 以二进制的方式转换成字符串或写入文件, 参数表示文件名, 文件名的后缀不能任意取

In [88]:
a.tofile("test.bin")

执行C语言程序可以将test.bin文件中的数据读取出来

In [89]:
%%file read_struct_array.c
#include <stdio.h>

struct person 
{
    char name[30];
    int age;
    float weight;
};

struct person p[3];

void main ()
{
    FILE *fp;
    int i;
    fp=fopen("test.bin","rb");
    fread(p, sizeof(struct person), 2, fp);
    fclose(fp);
    for(i=0;i<2;i++)
    {
        printf("%s %d %f\n", p[i].name, p[i].age, p[i].weight);
    }
}

Overwriting read_struct_array.c


In [90]:
!gcc read_struct_array.c -o read_struct_array.exe
!read_struct_array.exe

Zhang 40 75.500000
Li 24 65.199997


结构类型可以包含其他的结构类型

In [92]:
np.dtype([('f1', [('f2', np.int16)])])
# 字段为 f1 的结构, 

dtype([('f1', [('f2', '<i2')])])

    当某个字段为数组时,用元组的第三个元素表示形状

In [93]:
np.dtype([('f0', 'i4'), ('f1', 'f8', (2, 3))])

dtype([('f0', '<i4'), ('f1', '<f8', (2, 3))])

用字节偏移量定义结构数组: 

surname 结构的字段名, 值为字段的类型描述, 类型描述的第二个值表示以字节为单位的偏移量

In [94]:
np.dtype({'surname':('S25',0),'age':(np.uint8,25)})

dtype([('surname', 'S25'), ('age', 'u1')])

### 内存结构

数组对象是如何在内存中存储的?

**ndarray数据结构:**

1. dtype: 描述元素类型
1. data: 数据存储区域
1. strides: 轴元素间隔
1. dim count: 维数
1. dimension: 维度

In [95]:
a=np.array(np.arange(9).reshape(3,3),dtype=np.float32)
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

**stride 属性** 保存每个轴上相邻两个元素的地址差.

In [96]:
a.strides

(12, 4)

> 
一个单精度浮点数占4个字节,第0轴增加12个字节正好是3个单精度浮点数的总字节数,第一轴增加4个字节,正好是增加一个单精度浮点数

In [97]:
b=a[::,::2]
b

array([[0., 2.],
       [3., 5.],
       [6., 8.]], dtype=float32)

In [98]:
b.strides

(12, 8)

通过切片联系的数组a与数组b共享存储空间, 所以他们的strides属性保持着轴与轴的对应关系

In [99]:
c=a[[0,1]]
c

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

**元素的编址方式:**

Fortran 格式按列给元素地址编号, C 语言格式按行给元素地址编号, MATLAB也是按列给元素地址编号

In [100]:
a_for = np.array([[0,1,2],[3,4,5],[6,7,8]], dtype=np.float32, order="F")
a_for.strides

(4, 12)

数组的 flag 属性描述了其存储信息的一些属性

In [103]:
print(a.flags)
print( "c_contiguous:", a.flags.c_contiguous)
# OWNDATA : 是否享有完整的存储区域, 视图没有 

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
c_contiguous: True


In [104]:
a.T.flags
# 转置相当于改变了元素的编址方式

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [105]:
b.flags
# b 不享有完整的地址, 并且地址顺序不连续

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

**base 属性** 可以获得视图数组的原始数组

In [106]:
 id(b.base), id(a)

(2625172091568, 2625172091568)

**view 方法** 可以从同一块二进制数据区, 创建不同 dtype 类型的数组对象 ( 01 组合不同, 结果也变得不同)

In [107]:
a = np.array([[0, 1], [2, 3], [4, 5]], dtype=np.float32)
b = a.view(np.uint32)
c = a.view(np.uint8)

In [108]:
b

array([[         0, 1065353216],
       [1073741824, 1077936128],
       [1082130432, 1084227584]], dtype=uint32)

In [109]:
 c

array([[  0,   0,   0,   0,   0,   0, 128,  63],
       [  0,   0,   0,  64,   0,   0,  64,  64],
       [  0,   0, 128,  64,   0,   0, 160,  64]], dtype=uint8)

> http://zh.wikipedia.org/wiki/平方根倒数速算法

> 维基百科关于雷神之锤中使用`0x5f3759df`计算平方根倒数算法的解释

In [110]:
number = np.linspace(0.1, 10, 100)
y = number.astype(np.float32)  
x2 = y * 0.5
i = y.view(np.int32)  #❷
i[:] = 0x5f3759df - (i >> 1)  #❸
y = y * (1.5 - x2 * y * y)  #❹
np.max(np.abs(1 / np.sqrt(number) - y))  #❺

0.005045614041059743

In [111]:
#%figonly=雷神之锤中计算平方根倒数算法的绝对误差
import pylab as pl
pl.plot(number, 1/np.sqrt(number) - y, lw=2)
pl.ylabel(u"真实值与近似值的误差");

*** 
***

**带重叠的分块** 可以从一位数组创建对称矩阵

In [112]:
from numpy.lib.stride_tricks import as_strided
a = np.arange(6)
b = as_strided(a, shape=(4, 3), strides=(4, 4))
a

array([0, 1, 2, 3, 4, 5])

In [113]:
b
# 假设0,1,2,3,4,5 也表示内存地址的编号, b的第一个元素是0, 从上到下, 从左到右, 地址都会增加4
# 数组 a 与 b 共享存储结构, 并且 b 中的前两行有两个元素是重合的

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [114]:
a.strides, b.strides

((4,), (4, 4))